[features]
resolution = true
skip-lint = false

[programs.localnet]
fitstake_vault = "Y423PxcQ8DobRYRrWRCYG7XrRkfvhT7MyP8TWex1MxX"

[programs.devnet]
fitstake_vault = "Y423PxcQ8DobRYRrWRCYG7XrRkfvhT7MyP8TWex1MxX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/phantom-devnet.json"

[toolchain]
anchor_version = "0.30.1"
